// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Patients = sequelize.define('patients', {
    patientId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      defaultValue: Sequelize.literal('nextval(\'patients_patient_id_seq\'::regclass)'),
      allowNull: false,
    },
    firstName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    age: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    gender: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    contactInfo: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    medicalHistory: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    diagnosis: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    diagnosisType: {
      type: DataTypes.STRING,
      defaultValue: "mild",
    },
    pathology: {
      type: DataTypes.STRING,
    },
    insuranceCoverage: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    insuranceName: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'patients',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Patients.associate = (models) => {
    Patients.hasMany(models.appointments, {
      foreignKey: {
        name: 'patientIdKey',
        field: 'patient_id',
      },
      sourceKey: 'patientId',
      as: 'appointments',
    });
    Patients.hasMany(models.prescriptions, {
      foreignKey: {
        name: 'patientIdKey',
        field: 'patient_id',
      },
      sourceKey: 'patientId',
      as: 'prescriptions',
    });
  };

  return Patients;
};
